### ISSUE TITLE
Ensure the repository is always captured correctly

### ISSUE THREAD

**Issue by SensibleWood** [OAI/Tooling#3]
## User Story

As a user of tooling data I want the repository to be captured consistently across all sources.

## Detailed Requirement

There's a couple of instances where the repository is not captured correctly, for example:

```yaml
- source: IMPLEMENTATIONS.md
  name: KaiZen OpenAPI Parser
  homepage: https://github.com/RepreZen/KaiZen-OpenAPI-Parser
  language: Java
  curated_description: High-performance Parser, Validator, and Java Object Model for OpenAPI 3.x
  category: Low-Level tooling
```

This instance is specific to IMPLEMENATIONS.md processor - and could be tackled in [this array builder](https://github.com/OAI/Tooling/blob/develop/gulpfile.js/lib/processors/openapi-implementations-md-processor.js#L21) - but it would be good to implement in the main gulp file so it works across all sources.
